"""Reusable MDP term library (observations, rewards, terminations, events, commands, actions)."""

from genelab.mdp.actions import JointPositionAction, JointPositionActionCfg
from genelab.mdp.commands import (
    MotionCommand,
    MotionCommandCfg,
    MotionLoader,
    UniformVelocityCommand,
    UniformVelocityCommandCfg,
)
from genelab.mdp.curriculums import commands_vel, terrain_levels_vel
from genelab.mdp.events import (
    push_by_setting_velocity,
    reset_joints_by_offset,
    reset_joints_to_default,
    reset_root_state_uniform,
)
from genelab.mdp.noise import Gnoise, NoiseCfg, Unoise
from genelab.mdp.observations import (
    base_ang_vel,
    base_lin_vel,
    foot_air_time,
    foot_contact,
    foot_contact_forces,
    generated_commands,
    height_scan,
    joint_pos_rel,
    joint_vel_rel,
    last_action,
    motion_anchor_ori_b,
    motion_anchor_pos_b,
    projected_gravity,
    robot_body_ori_b,
    robot_body_pos_b,
    sensor_data,
)
from genelab.mdp.rewards import (
    action_rate_l2,
    body_angular_velocity_penalty,
    feet_air_time,
    feet_clearance,
    feet_slip,
    feet_swing_height,
    flat_orientation_l2,
    joint_acc_l2,
    joint_pos_limits,
    motion_global_anchor_orientation_error_exp,
    motion_global_anchor_position_error_exp,
    motion_global_body_angular_velocity_error_exp,
    motion_global_body_linear_velocity_error_exp,
    motion_relative_body_orientation_error_exp,
    motion_relative_body_position_error_exp,
    soft_landing,
    track_angular_velocity_z_exp,
    track_linear_velocity_xy_exp,
    upright_exp,
    variable_posture,
)
from genelab.mdp.terminations import (
    bad_anchor_ori,
    bad_anchor_pos_z_only,
    bad_motion_body_pos_z_only,
    bad_orientation,
    root_height_below,
    time_out,
)

__all__ = [
    "Gnoise",
    "JointPositionAction",
    "JointPositionActionCfg",
    "MotionCommand",
    "MotionCommandCfg",
    "MotionLoader",
    "NoiseCfg",
    "UniformVelocityCommand",
    "UniformVelocityCommandCfg",
    "Unoise",
    "action_rate_l2",
    "bad_anchor_ori",
    "bad_anchor_pos_z_only",
    "bad_motion_body_pos_z_only",
    "bad_orientation",
    "base_ang_vel",
    "base_lin_vel",
    "body_angular_velocity_penalty",
    "commands_vel",
    "feet_air_time",
    "feet_clearance",
    "feet_slip",
    "feet_swing_height",
    "flat_orientation_l2",
    "foot_air_time",
    "foot_contact",
    "foot_contact_forces",
    "generated_commands",
    "height_scan",
    "joint_acc_l2",
    "joint_pos_limits",
    "joint_pos_rel",
    "joint_vel_rel",
    "last_action",
    "motion_anchor_ori_b",
    "motion_anchor_pos_b",
    "motion_global_anchor_orientation_error_exp",
    "motion_global_anchor_position_error_exp",
    "motion_global_body_angular_velocity_error_exp",
    "motion_global_body_linear_velocity_error_exp",
    "motion_relative_body_orientation_error_exp",
    "motion_relative_body_position_error_exp",
    "projected_gravity",
    "push_by_setting_velocity",
    "reset_joints_by_offset",
    "reset_joints_to_default",
    "reset_root_state_uniform",
    "robot_body_ori_b",
    "robot_body_pos_b",
    "root_height_below",
    "sensor_data",
    "soft_landing",
    "terrain_levels_vel",
    "time_out",
    "track_angular_velocity_z_exp",
    "track_linear_velocity_xy_exp",
    "upright_exp",
    "variable_posture",
]
